---
title: "recalc geometeric mean"
author: "Becky Forgrave"
date: "2025-08-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(googledrive)
library(mnsentinellakes)
library(readxl)
library(here)
library(FSA) # for geomean() function
library(janitor) 

here = here() # sets base directory as where this .Rmd file is saved

# clean up workspace
rm(list = ls())

```

## MPRB ####
```{r load data}

# get data from google drive
setwd("G:/Shared drives/MSP LTER - Public/Q2 - Lakes and Watersheds/Q2.2 - Lakes & Surface Waters/TCMA Lake Research/Research initiatives/Beaches")


mprb_raw <- read_excel("./Received data/Minneapolis Parks Board/MPRB_beaches_compiled.xlsx") %>%
  janitor::clean_names()

str(mprb_raw)

unique(mprb_raw$beach_name)


# reformat and rearrange
mprb <- mprb_raw %>%
  mutate(date = as.Date(date, format = "%m/%d/%Y")) %>%
  mutate(units = "cfu/100mL") %>%
  select(beach_name, date, ecoli_sample_a, ecoli_sample_b, ecoli_dup, ecoli_30d_gm, units, beach_closure, closure_reason, notes)   # choose columns to move forward with


# remove <1s in data and convert to numeric
expected <- length(which(mprb[,3:5] == "<1")) +  length(which(mprb[,3:5] == "1")) # get number of <1 and 1 in all data columns

mprb <- mprb %>%
  mutate(across(.cols = 3:5,
                .fns = ~ str_replace(string = .x, pattern = "<1", replacement = "1"))) %>%
  mutate(across(.cols = 3:5,
                 .fns = as.numeric))

length(which(mprb[,3:5] == "1"))  == expected # check that all converted correctly --> True



str(mprb)
summary(mprb)


# join with beach list to get DOWs
mprb_beaches <- read.csv("Beach_list_DOWs.csv") %>%
  filter(monitoring_org == "MPRB") %>%
  mutate(DOW = fixlakeid(DOW)) %>%
  select(beach_name, lake, DOW)


mprb <- left_join(mprb, mprb_beaches)

```

```{r calculations with MPRB data}

# create new column to hold calculated values
mprb$ecoli_1dGM <- 0
mprb$ecoli_30dGM <- 0


# make list of beaches to loop through
beachlist <- unique(mprb$beach_name)


# new dataframe to put data in
mprb_long <-  mprb %>%
  pivot_longer(
    cols = c(ecoli_sample_a, ecoli_sample_b, ecoli_dup),
    names_to = "sampleID",
    values_to = "ecoli"
  )


# NEED TO MAKE IT LONG --> TOO MANY COLUMNS

# loop through list of beaches and calcualte 30day GM
for (i in 1:length(beachlist)) {
 
  # select one beach
  onebeach <- mprb %>%
    filter(beach_name == beachlist[i])

 # manipulate only that beach to calculate geometric means 
  for (i in 1:length(onebeach$date)) {

    intervalstart <- as.POSIXct(onebeach$date[i] - 30) # start 30 days before sampling date
    intervalend <-  as.POSIXct(onebeach$date[i])
  
    # select all E coli measurements for one day
    oneday <-  onebeach %>%
      filter(date == intervalend)
    
    # calculate 1 day geometric mean and add it to column in df
    onebeach$ecoli_1dGM[i] <- round(geomean(oneday$ecoli, na.rm = TRUE), digits = 1)
    
    
    # select all E coli measurements in range
    span30d <-  onebeach %>%
      filter(date >= intervalstart & date <= intervalend)
    
    # calculate 30-day geometric mean and add it to column in df
    onebeach$ecoli_30dGM[i] <- round(geomean(span30d$ecoli, na.rm = TRUE), digits = 1)
    
  }

  mprb_new <- bind_rows(mprb_new, onebeach) # recombine beaches

}

mprb_new$ecoli_30d_gm == mprb_new$gm30day # don't always match up
# do we use our calculations or theirs? --> ours to keep it consistent



mprb_new$closureYN <- 0
mprb_new$closure_reason <- ""

mprb_new <- mprb_new %>%
  mutate(
    closureYN = if_else(
      condition = ecoli_1dGM > 1260,
      true = "Y",
      false = "N")
  ) %>%
  mutate(
    closure_reason = if_else(
      condition = ecoli_1dGM > 1260,
      true = "ecoli_1dayGM",
      false = NA)
  ) %>% 
  mutate(
    closureYN = if_else(
      condition = ecoli_30dGM > 126,
      true = "Y",
      false = "N")
  ) %>%
  mutate(
    closure_reason = if_else(
      condition = ecoli_30dGM > 126,
      true = "ecoli_30dayGM",
      false = NA)
  ) 


mprb_new$closureYN == mprb_new$closedYN # not exaclty the same (adds 16 closures not in original data)


mprb_clean <- mprb_new %>%
  select(beach, DOW, date, ecoli_1dGM, ecoli_30dGM, units, closureYN, closure_reason)


# save to GitHub
write_csv(mprb_clean, file = here("./data-organization/individual-datasets/MPRB_clean_082225.csv"))

```

