---
title: "Hennepin county data cleaning"
author: "Becky Forgrave"
date: "2025-09-23"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(googledrive)
library(readxl)
library(here)
library(FSA) # for geomean() function
library(janitor) # for row_to_names() fucntion
```

# Append all --> export to OpenRefine to fix misspellings in names

```{r load data 1}

setwd("G:/Shared drives/MSP LTER - Public/Q2 - Lakes and Watersheds/Q2.2 - Lakes & Surface Waters/TCMA Lake Research/Research initiatives/Beaches/Received data/Hennepin County/")

# 2007-2012
hc2007 <- read.csv("./bf_annotated/2007 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  filter(date != "")  %>% # remove empty cells (relic from excel)
  select(date, beach, lake, e_coli_100ml, comments) 

hc2008 <- read.csv("./bf_annotated/2008 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  filter(date != "") %>%
  select(date, beach, lake, e_coli_100ml, comments)

hc2009 <- read.csv("./bf_annotated/2009 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  filter(date != "") %>%
  select(date, beach, lake, e_coli_100ml, comments)

hc2010 <- read.csv("./bf_annotated/2010 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  filter(date != "") %>%
  select(date, beach, lake, e_coli_100ml, comments)

hc2011 <- read.csv("./bf_annotated/2011 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  filter(date != "") %>%
  select(date, beach, lake, e_coli_100ml, comments)

hc2012 <- read.csv("./bf_annotated/2012 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  filter(date != "") %>%
  rename(beach = beach_park) %>%
  select(date, beach, lake, e_coli_100ml, comments)

# JOIN THEM
hc_2007_2012 <- rbind(hc2007, hc2008, hc2009, hc2010, hc2011, hc2012)


hc_2007_2012 <- hc_2007_2012 %>%
  mutate(date = as.Date(date, format="%m/%d/%Y"))
  

```

```{r load data 2}

# 2013-2016
hc2013 <- read.csv("./bf_annotated/2013 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2014 <- read.csv("./bf_annotated/2014 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2015 <- read.csv("./bf_annotated/2015 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2016 <- read.csv("./bf_annotated/2016 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

# JOIN THEM
hc_2013_2016 <- rbind(hc2013, hc2014, hc2015, hc2016)

hc_2013_2016 <- hc_2013_2016 %>%
  mutate(date = as.Date(date, format="%m/%d/%Y"))


```

```{r load data 3 }

# same columns as above but will need to remove L, R, C from beach names
hc2017 <- read_xlsx("2017_Beach_Sample_Results.xlsx") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  # mutate(date = as.Date(date))
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2018 <- read_xlsx("2018_Beach_Sample_Results.xlsx") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2019 <- read_xlsx("2019_Beach_Sample_Results.xlsx") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2020 <- read_xlsx("2020_Beach_Sample_Results.xlsx") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2021 <- read_xlsx("2021_Beach_Sample_Results.xlsx") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)

hc2022 <- read_xlsx("Annotated_2022_Beach_Sample_Results.xlsx") %>%
  janitor::clean_names() %>%
  rename(date = smple_date) %>%
  select(date, beach,  cfu, resmpl_req, open_closed, comments)



# JOIN THEM
hc_2017_2022 <- rbind(hc2017, hc2018, hc2019, hc2020, hc2021, hc2022)



hc_2017_2022 <- hc_2017_2022  %>%
  mutate(date = as.Date(date, format="%Y-%d-%m"))

```

```{r}

hc2023 <- read.csv("./bf_annotated/2023 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  rename(date = collection_date) %>%
  rename(beach = sample_description) %>%
  select(date, beach,  result, units)


hc2024 <- read.csv("./bf_annotated/2024 hennepin ecoli.csv") %>%
  janitor::clean_names() %>%
  rename(date = date_sampled) %>%
  rename(beach = sample_description) %>%
  select(date, beach,  result, units)


hc_2023_2024 <- rbind(hc2023, hc2024)

hc_2023_2024 <- hc_2023_2024 %>%
  mutate(date = as.Date(date, format="%m/%d/%Y"))

```


```{r bulk edit and combine all}

# bulk edit
hc_2007_2012 <- hc_2007_2012 %>%
  rename(ecoli = e_coli_100ml) %>%
  mutate(units = "cfu/100mL")

hc_2013_2016 <- hc_2013_2016 %>%
  rename(ecoli = cfu) %>%
  mutate(units = "cfu/100mL")

hc_2017_2022 <- hc_2017_2022 %>%
  rename(ecoli = cfu) %>%
  mutate(units = "cfu/100mL")

hc_2023_2024 <- hc_2023_2024 %>%
  rename(ecoli = result) %>%
  mutate(units = "mpn/100mL")


# combine all
hc_all <- full_join(hc_2007_2012, hc_2013_2016)
hc_all <- full_join(hc_all, hc_2017_2022)
hc_all <- full_join(hc_all, hc_2023_2024)



# export combined data
write.csv(hc_all, file = "Hennepin_combined_raw.csv", row.names = FALSE)


```
 # export to edit beach names in open refine (remove L/R/C and fix misspellings)
 
 
# Read back into R 
```{r covert column formats}

hc <- read.csv("Hennepin_combined_openrefine.csv") %>%
  mutate(date = as.Date(date)) %>%
  filter(!is.na(ecoli)) %>%
  rename(BeachName = beach) %>%
  select(date, BeachName, ecoli,units)

str(hc)
summary(hc)

# fix date errors
hc$date[which(hc$date == "3009-06-30")] <- "2009-06-30"
hc$date[which(hc$date == "2107-06-21")] <- "2017-06-21"

# fix last naming error
hc$BeachName[hc$BeachName == "Walden Trail"] <- "Nocomo"

```



```{r convert all values to numeric}


# Change values with < or > and convert them to the value itself
hc <- hc %>%
  mutate(ecoli = str_remove_all(ecoli, "<|>"))


# convert numeric columns from chr --> num
hc  <- hc %>%
  mutate(ecoli= as.numeric(ecoli))

# still more nas
nas <- hc %>%
  filter(is.na(ecoli))

str(hc)
summary(hc)

hc <- hc %>%
  filter(!is.na(ecoli))


# head(hc %>%  arrange(ecoli), 20)
# tail(hc %>%  arrange(ecoli), 20) # do we think super high values are real??

# remove NAs and -9999 values
hc <- hc %>%
  filter(ecoli > 0 )


summary(hc)

```

```{r calculate geometric means}


# create new column to hold calculated values
hc$Ecoli_1dGM <-0
hc$Ecoli_30dGM <- 0

hc_new <- data.frame()

# loop through list of beaches
hcbeachlist <- unique(hc$BeachName)

for (i in 1:length(hcbeachlist)) {
  
beach <- hc %>%
  filter(BeachName == hcbeachlist[i])

  # loop through each day
  for (i in 1:length(beach$date)) {
    intervalstart <- as.POSIXct(beach$date[i] - 30) # start 30 days before sampling date
    intervalend <-  as.POSIXct(beach$date[i])
  
    # select all E coli measurements for one day
    oneday <-  beach %>%
      filter(date == intervalend)
    
    # calculate 1 day geometric mean and add it to column in df
    beach$Ecoli_1dGM[i] <- round(geomean(oneday$ecoli, na.rm = TRUE), digits = 1)
    
    # select all E coli measurements in 30 day range
    span30d <-  beach %>%
      filter(date >= intervalstart & date <= intervalend)
    
    # calculate 30-day geometric mean and add it to column in df
    beach$Ecoli_30dGM[i] <- round(geomean(span30d$ecoli, na.rm = TRUE), digits = 1)
    
  }

hc_new <- rbind(hc_new, beach)

}


```

```{r fill additional columns}

# add columns to match master dataset--------------------
henn <- hc_new %>%
  filter(!is.na(Ecoli_1dGM)) %>%
  mutate(
    ClosureYN = "N",
    ClosureReason = NA,
    MonitoringOrg = "HennepinCo") %>%
  rename(Ecoli_units = units)


# add DOWs--------------------

hennDOWs <- read.csv("Hennepin_beach_dow_list.csv") %>%
  mutate(DOW = fixlakeid(DOW))

henn <- left_join(henn, hennDOWs)




# find a label beach closures-------------------------------

henn <- henn  %>%
  mutate(
    ClosureYN = if_else(
      condition = Ecoli_1dGM > 1260,
      true = "Y",
      false = "N")
  ) %>%
  mutate(
    ClosureReason = if_else(
      condition = Ecoli_1dGM > 1260,
      true = "ecoli_1dayGM",
      false = NA)
  ) %>% 
  mutate(
    ClosureYN = if_else(
      condition = Ecoli_30dGM > 126,
      true = "Y",
      false = "N")
  ) %>%
  mutate(
    ClosureReason = if_else(
      condition = Ecoli_30dGM > 126,
      true = "ecoli_30dayGM",
      false = NA)
  ) 

# rearragne columns
henn <- henn %>%
  rename(Date = date) %>%
  select(BeachName, DOW, Date, MonitoringOrg, Ecoli_1dGM, Ecoli_30dGM, Ecoli_units, ClosureYN, ClosureReason)

```

```{r save data}


# upload to Google Drive 
setwd("G:/My Drive/Research/beaches/data/processed/")


write.csv(henn, file = "HennepinCo_100225.csv", row.names = FALSE)

```