---
title: "beaches_and_water_level"
author: "Becky Forgrave"
date: "2025-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mnsentinellakes)

```

```{r}

# define function (from MN sentinel lakes but with updated url)
waterleveldownload.new <- function (lakeid, metric = TRUE) 
  {
    if (lakeid == "47004901") {
      wtrlvldata = as.data.frame(data.table::fread(paste0("http://files.dnr.state.mn.us/cgi-bin/lk_levels_dump.cgi?format=csv&id=47004900")))
    }
    else {
      wtrlvldata = as.data.frame(data.table::fread(paste0("https://maps.dnr.state.mn.us/cgi-bin/lakefinder/water_levels_export.cgi?format=csv&id=", 
                                                          lakeid)))
    }
    if (nrow(wtrlvldata) > 0) {
      wtrlvldata$ELEVATION = as.numeric(wtrlvldata$ELEVATION)
      wtrlvldata$READ_DATE = as.Date(as.character(wtrlvldata$READ_DATE))
      if (metric == TRUE) {
        wtrlvldata["elev_m"] = round(as.numeric(wtrlvldata$ELEVATION * 
                                                  0.3048), digits = 2)
        wtrlvldf = data.frame(Lake = mnsentinellakes::lakeid2name(lakeid), 
                              LakeId = lakeid, Date = wtrlvldata$READ_DATE, 
                              Elevation_m = wtrlvldata$elev_m, Datum_Adj = wtrlvldata$DATUM_ADJ)
      }
      else {
        wtrlvldf = data.frame(Lake = mnsentinellakes::lakeid2name(lakeid), 
                              LakeId = lakeid, Date = wtrlvldata$READ_DATE, 
                              Elevation_ft = wtrlvldata$ELEVATION, Datum_Adj = wtrlvldata$DATUM_ADJ)
      }
    }
    else {
      wtrlvldf = NULL
      warning("No water level data available.")
    }
    return(wtrlvldf)
  }


test <-  waterleveldownload.new("27001800") # hiawatha

```

```{r get list of all DOws}

setwd("G:/My Drive/Research/beaches/data")

beachlist <- read.csv("BeachList.csv") %>%
  filter(!is.na(DOW)) %>%
  mutate(DOW = fixlakeid(DOW))

dowlist <- unique(beachlist$DOW)


```

```{r loop throgh all DOws to get water level}

waterlevelall <- data.frame()
  
for( i in 1:length(dowlist)) { 
  
  dow <- dowlist[i]
  onewl <- waterleveldownload.new(dow)
  waterlevelall <- bind_rows(waterlevelall, onewl)
}


waterlevelall  <- waterlevelall  %>%
  rename(DOW = LakeId)


```

```{r save to file}

write.csv(waterlevelall, "./other_variables/water_level/allwaterleveldata.csv", row.names = FALSE)

```
