---
title: "beaches_and_shoreline"
author: "Becky Forgrave"
date: "2025-11-07"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(patchwork)
library(mnsentinellakes)

```

```{r load compiled beach data}

setwd("G:/My Drive/Research/beaches/data/")

beaches <- read.csv("./processed/combined/All_beaches_new_100225_openrefine.csv") %>%
  janitor::clean_names() %>%
  filter(!is.na(dow)) %>% # remove swim ponds (don't have DOWs)
  mutate(dow = fixlakeid(dow)) %>%
  mutate(date = as.POSIXct(date, format = "%Y-%m-%d"))  %>%
  mutate(year = year(date)) %>%
  mutate(month = month(date)) %>%
  mutate(jday = yday(date)) %>%
  mutate(week = week(date)) 
  #filter(date > "2010-01-01" & date < "2025-01-01") # select to dates with most data

closed <- beaches %>%
  filter(closure_yn == "Y")


```

```{r load spatial data}


lakes


nlcd


```

```{r shoreline buffers}

# create buffer polygon


# extract land cover and summarize

```

