---
title: "Beach data initial explore"
author: "Becky Forgrave"
date: "2025-10-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(patchwork)
library(mnsentinellakes)

```

```{r load compiled beach data}

setwd("G:/My Drive/Research/beaches/data/")

# Two beaches don't have a DOW - Minnetonka swim pond and Elm creek swim pond
# messes up fixlakeid() --> remove

beaches <- read.csv("./processed/combined/All_beaches_new_100225_openrefine.csv") %>%
  janitor::clean_names() %>%
  filter(!is.na(dow)) %>% # remove swim ponds (don't have DOWs)
  mutate(dow = fixlakeid(dow)) %>%
  mutate(date = as.POSIXct(date, format = "%Y-%m-%d"))  %>%
  mutate(year = year(date)) %>%
  mutate(month = month(date)) %>%
  mutate(jday = yday(date)) %>%
  # filter(date > "2010-01-01" & date < "2025-01-01") # select to dates with most data

closed <- beaches %>%
  filter(closure_yn == "Y")

```

```{r recalculate closures with new thresholds}


beaches_new <- beaches   %>%
  mutate(
    closure_yn = if_else(
      condition = ecoli_1d_gm > 235,
      true = "Y",
      false = "N")
  ) %>%
  mutate(
    closure_reason = if_else(
      condition = ecoli_1d_gm > 235,
      true = "ecoli_1dayGM",
      false = NA)
  ) %>% 
  mutate(
    closure_yn = if_else(
      condition = ecoli_30d_gm > 126,
      true = "Y",
      false = "N")
  ) %>%
  mutate(
    closure_reason = if_else(
      condition = ecoli_30d_gm > 126,
      true = "ecoli_30dayGM",
      false = closure_reason)
  ) 


# this overprints the 30day on top of the 1 day closures --> what to do if both conditions are met?


closed_new <- beaches_new %>%
  filter(closure_yn == "Y")

  
```



# dataset basics
```{r data exploration}

length(unique(beaches$beach_name))
# 81 beaches

length(unique(beaches$dow))
# 59 lakes 



ggplot(closed, aes(x = closure_reason)) + 
  geom_bar()


ggplot(closed_new, aes(x = closure_reason)) + 
  geom_bar()

# how many closures in past 15 years from each type
closures.summary <- closed %>% 
  group_by(closure_reason) %>%
    summarize(n = n(),
              perc = round((n/length(closed$beach_name))*100,digits = 2))
closures.summary


```


```{r which beaches close the most often}

# table of number of beach closures per beach in whole dataset
beach.summary <- beaches %>% 
  group_by(beach_name) %>%
    summarize(startYear = min(year), 
              endYear = max(year),
              numSamples = n()) 


closed.summary <- closed %>% 
  group_by(beach_name) %>%
    summarize(numClosures = n()) 



combined.summary <- left_join(beach.summary, closed.summary) %>%
  mutate(percClosed = round((numClosures/numSamples) *100)) %>%
  arrange(desc(percClosed))
combined.summary


mostclosedlist <- combined.summary$beach_name[1:10]


# none that are never closed --> NA (not zero)

setwd("G:/My Drive/Research/beaches/data/processed")
write.csv(combined.summary, "./combined/beachSummary.csv", row.names = FALSE)


closed.summary.detailed <- closed %>% 
  group_by(beach_name, year) %>%
    summarize(numClosures = n()) 



################# GET average length of closure --> how? using interval fucntion???
# will depend on how often it is sampled


```

```{r histograms}


closed.by.year <-  beaches %>%
  filter(closure_yn == "Y") %>% 
  group_by(year) %>%
    summarize(nClosures = n()) 


beaches.by.year <- beaches %>% 
  group_by(year) %>%
    summarize(nSamples = n())


year.summary  <- left_join(beaches.by.year , closed.by.year) %>%
  mutate(percClosed = round((nClosures/nSamples) *100)) %>%
  arrange(desc(percClosed))



percclosedplot <- ggplot(year.summary, aes(x=year, y=percClosed)) +
  geom_col(fill = "darkorange") + 
  ylab("% of days closed") + xlab("") +
  xlim(2005, 2025) + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  theme(text = element_text(size = 20))


# plot number of samples each year
percsamplesplot <- ggplot(year.summary, aes(x=year, y=nSamples)) +
  geom_col(fill = "darkgreen") + 
  ylab("Samples collected") +  xlab("") +
  xlim(2005, 2025) + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  theme(text = element_text(size = 20))

histplot <- percclosedplot  / percsamplesplot 
histplot


setwd("G:/My Drive/Research/beaches/output/figures/")

ggsave("yearlyclosureshist.png", plot = histplot, width = 10, height = 5, units = "in")



```

```{r plots}

# whole time series
ggplot(beaches, aes(x=date, y=ecoli_1d_gm)) +
  geom_point() +
  ylim(0,2500)

# throughout monitoring season
ggplot(beaches, aes(x=jday, y=ecoli_1d_gm, color = closure_yn)) +
  geom_point() +
  ylim(0,2500)
# more closures later in season but they can be any time


ggplot(beaches, aes(x=jday, y=ecoli_1d_gm)) +
  geom_point() +
  geom_smooth() + 
  ylim(0,2500)


```
```{r averages}

# average all beaches for each day (each week?)
avg_ecoli <- beaches %>%
  group_by(year, week) %>%
  summarize(ecoli_allbeachesmean = mean(ecoli_1d_gm))

ggplot(avg_ecoli, aes(x=week, y=ecoli_allbeachesmean, group = year, color = year)) +
  geom_point() +
  geom_smooth(se= FALSE) 


# whole time series
ggplot(avg_ecoli, aes(x=Date, y=ecoli_allbeachesmean)) +
  geom_point() +
  ylim(0,2500)


# compare each beach to the average
# is this worthwhile?

# look in literature for ideas

```


 # CLIMATE
```{r monthly climate data}

# mprecip <- read.csv("./other_variables/precip_by_month.csv") %>%
#   mutate(Annual_mm = Annual * 25.4) %>%
#   mutate(May_mm = May * 25.4) %>%
#   mutate(Jun_mm = Jun * 25.4) %>%
#   mutate(Jul_mm = Jul * 25.4) %>%
#   mutate(Aug_mm = Aug * 25.4) %>%
#   mutate(Sep_mm = Sep * 25.4) %>%
#   select(Year, Annual_mm, May_mm, Jun_mm, Jul_mm, Aug_mm, Sep_mm) %>%
#   filter(Year > 2009)
# 
# 
# mtempavg <- read.csv("./other_variables/avg_temp_monthly.csv")  %>%
#   filter(Year > 2009) 
# 
#  
# mtempmax <- read.csv("./other_variables/max_temp_monthly_mean.csv")  %>%
#   filter(Year > 2009)

```

```{r daily climate data}

setwd("G:/My Drive/Research/beaches/data/")

dclim <- read.csv("./other_variables/daily_precip.csv") %>%
  janitor::clean_names() %>%
  mutate(date = as.Date(date, format = "%Y-%m-%d")) %>%
  mutate(max_temp_degC = (as.numeric(maximum_temperature_degrees_f) - 32) *(5/9)) %>%
  mutate(min_temp_degC = (as.numeric(minimum_temperature_degrees_f) - 32) *(5/9)) %>%
  mutate(precip_mm = as.numeric(precipitation_inches)* 25.4) %>%  # Trace precip (T) becomes NA
  select(date, precip_mm, max_temp_degC, min_temp_degC) %>%
  filter(date >= "2010-01-01" & date < "2025-01-01")


dclim$ante2dptot <- 0
dclim$ante2avgmaxt <- 0

# rolling 5 day climate
for (i in 1:length(dclim$date)) {
  intervalstart <- as.POSIXct(dclim$date[i] - 2) #rolling window 5 days before
  intervalend <-  as.POSIXct(dclim$date[i])
  
  span2d <-  dclim %>%
    filter(date >= intervalstart & date <= intervalend) # select all data 5 days 
  
  dclim$ante2dptot[i] <- sum(span2d$precip_mm, na.rm = TRUE)
  dclim$ante2avgmaxt[i] <- mean(span2d$max_temp_degC, na.rm = TRUE)
}

summary(dclim)

  
# # summarize weekly --> rolling average is better
# dprecip <- dprecip %>% 
#     mutate(w = week(date)) %>%
#     group_by(yw = paste(year(date), week(date))) %>%
#     mutate(weeklyPtotal = sum(precip_mm, na.rm = T)) %>%
#     mutate(weeklyavgTmax = mean(max_temp_degC, na.rm = T)) %>%
#     mutate(weeklyavgTmin= mean(min_temp_degC, na.rm = T)) %>%
#     ungroup()
# 
# wprecip <- dprecip %>%
#   select(yw, w, weeklyPtotal, weeklyavgTmax, weeklyavgTmin)
# 
# wprecip<- unique(wprecip)

```

```{r explore weekly precip}
# 
# ggplot(wprecip, aes(x=w, y=ante5dptot)) + 
#   geom_point() 
# 
# ggplot(wprecip, aes(x=yw, y=ante5dptot)) + 
#   geom_point()  $# too much data



```

```{r weekly precip data + ecoli}
 
combined <- left_join(beaches, dclim)

combined <- combined %>%
  mutate(logecoli = log10(ecoli_1d_gm))

precipplot <- ggplot(combined, aes(x=ante2dptot, y=logecoli)) + 
  geom_point() + 
  geom_smooth() +
  xlim(0,90) +
  ylim(0,3.5) + 
  ylab("log E. coli (cfu/100mL)") +
  xlab("48-hour antecedent precipitation (mm)") +
  theme_bw() +
  theme(text=element_text(size = 20))


# higher ecoli with more precipitation up to a point but then it decreases (dilution?)
# hard to get temp in there too as a variable

tempplot <- ggplot(combined, aes(x=ante2avgmaxt, y=logecoli)) + 
  geom_point() + 
  geom_smooth() +
  ylim(0,3.5) + 
  ylab("log E. coli (cfu/100mL)") +
  xlab("48-hour average daily maximum temperature (C)") +
  theme_bw() +
  theme(text=element_text(size = 20))

setwd("G:/My Drive/Research/beaches/output/figures/")

ggsave("precipecoliplot.png", plot = precipplot, width = 8, height = 5, units = "in")
ggsave("tempecoliplot.png", plot = tempplot, width = 8, height = 5, units = "in")

```


```{r precip specifics}

# closures by year
closed.plot <- ggplot(closed, aes(x=Year)) + 
  geom_bar(fill = "grey40") + 
  theme_bw() + 
  xlim(2009,2025) +
  ylab("Number of beach closures")

# annual precip
precip.plot <- ggplot(precip, aes(x=Year, y=Annual_mm)) + 
  geom_line(linewidth=2, color="blue") +
  # ylim(0, 1200) +  
  xlim(2009,2025) +
  theme_bw()

precip.plot /closed.plot 

# monthly precip
monthlyprecip.plot <- ggplot(precip, aes(x=Year)) + 
  geom_line(aes(y=May_mm), color = "lightblue",linewidth = 2) +
  geom_line(aes(y=Jun_mm), color = "deepskyblue",linewidth = 2) +
  geom_line(aes(y=Jul_mm), color = "steelblue",linewidth = 2) +
  geom_line(aes(y=Aug_mm), color = "blue",linewidth = 2) +
  geom_line(aes(y=Sep_mm), color = "darkblue",linewidth = 2) +
  ylab("Montly Precip (mm)") 

  
monthlyprecip.plot /closed.plot 


```

```{r temperature}

# calculate aveage summer temp

tempavg$Summer <- 0
for( i in 1:length(tempavg$Year)) {
  tempavg$Summer[i] <- mean(tempavg$May[i], tempavg$Jun[i], tempavg$Jul[i], tempavg$Aug[i])
}

tempavg.plot <- ggplot(tempavg, aes(x=Year, y=Summer)) + 
  geom_line(color = "gold", linewidth = 2) +
  xlim(2009,2025) +
  ylab("Mean SummerTemp (deg F)") +
  theme_bw()


monthlytempavg.plot <- ggplot(tempavg, aes(x=Year)) + 
  geom_line(aes(y=May), color = "darkgreen",linewidth = 2) +
  geom_line(aes(y=Jun), color = "green",linewidth = 2) +
  geom_line(aes(y=Jul), color = "gold",linewidth = 2) +
  geom_line(aes(y=Aug), color = "darkorange",linewidth = 2) +
  geom_line(aes(y=Sep), color = "red",linewidth = 2) +
  ylab("Average Monthly Temperature (deg F)") +
  theme_bw()


# summer average max temperature
tempmax$Summer <- 0
for( i in 1:length(tempmax$Year)) {
  tempmax$Summer[i] <- mean(tempmax$May[i], tempmax$Jun[i], tempmax$Jul[i], tempmax$Aug[i])
}

tempmax.plot <- ggplot(tempmax, aes(x=Year, y=Summer)) + 
  geom_line(color = "red", linewidth = 2) +
  xlim(2009,2025) +
  ylab("Summer Maximum Temp (deg F)") +
  theme_bw()


monthlytempmax.plot <- ggplot(tempmax, aes(x=Year)) + 
  geom_line(aes(y=May), color = "darkgreen",linewidth = 2) +
  geom_line(aes(y=Jun), color = "green",linewidth = 2) +
  geom_line(aes(y=Jul), color = "gold",linewidth = 2) +
  geom_line(aes(y=Aug), color = "darkorange",linewidth = 2) +
  geom_line(aes(y=Sep), color = "red",linewidth = 2) +
  ylab("Maximum Monthly Temperature (deg F)") 



monthlyavgtemp.plot/ monthlyprecip.plot /closed.plot 

tempavg.plot / precip.plot /closed.plot 

```

```{r seasonality of ecoli closures}

# closures by year
 ggplot(beaches, aes(x=Julian, y=Ecoli_1dGM, color = ClosureYN)) + 
  geom_point()
  

```

# WATERSHEDS and lakes

```{r lake wq data}

setwd("G:/My Drive/Research/watersheds")

# clarity
clarity <- read.csv("Timeseries_v6_ALLDOW.csv") %>%
  mutate(date = as.Date(sampleDate)) %>%
  mutate(dow = fixlakeid(DOW)) %>%
  filter(parameter == "secchi.m") %>%
  mutate(year = sampleYear)%>%
  mutate(week = week(date))


beachsecchi <- left_join(beaches, clarity)

ggplot(beachsecchi, aes(x=result, y=ecoli_1d_gm)) +
  geom_point() + 
  geom_smooth(method = lm) +
  xlab("Yearly average Secchi depth (m)") + 
  ylab("Yearly average E.coli (mpn/100mL)")




# mean ecoli for each beach, each week, each year --> is this a useful metric?
weeklyavgecolibybeach <- beaches %>%
  group_by(week, year, dow) %>%
  summarize(avgEcoli = mean(ecoli_1d_gm)) %>%
  ungroup()

weeklyavgclarity <- clarity %>%
  group_by(week, dow, year) %>%
  summarize(avgSecchi = mean(result)) %>%
  ungroup()


weeklyavgecolibybeach <- left_join(weeklyvgecolibybeach, weeklyavgclarity)

secchiplot <- ggplot(avgecolibybeach, aes(x=avgSecchi, y=log10(avgEcoli))) +
  geom_point() + 
  geom_smooth(method = lm) +
  xlab("Secchi depth (m)") + 
  ylab("log E.coli (mpn/100mL)") + 
  xlim(0,10) + 
  ylim(0, 2) +
  theme_bw() +
  theme(text=element_text(size = 20))

setwd("G:/My Drive/Research/beaches/output/figures/")

ggsave("secchiecoliplot.png", plot = secchiplot, width = 8, height = 5, units = "in")



# higher ecoli in shallower lakes --> or just cloudier ones?

sec.lm <- lm(avgEcoli~ avgSecchi, data= avgecolibybeach)
summary(sec.lm)
# nope


# yearly averages
yearlyavgecolibybeach <- beaches %>%
  group_by(year, dow) %>%
  summarize(avgEcoli = mean(ecoli_1d_gm)) %>%
  ungroup()

yearlyavgclarity <- clarity %>%
  group_by(dow, year) %>%
  summarize(avgSecchi = mean(result)) %>%
  ungroup()

yearlyavgecolibybeach <- left_join(yearlyavgecolibybeach, yearlyavgclarity)


```
```{r lake parameters}

setwd("G:/My Drive/Research/watersheds")


mls <- read.csv("MLS3_openrefine10-23-23.csv") %>%
  filter(!is.na(DOW)) %>%
  mutate(dow = fixlakeid(DOW))

lakeparams <- mls %>%
  select(LAKENAME, dow, LakeArea.ac, LittoralArea.ac, MeanDepth.m, MaxDepth.m)

lakeparams <- left_join(avgecolibybeach, lakeparams)

ggplot(lakeparams, aes(x=LakeDepth.m, y=avgEcoli)) +
  geom_point() + 
  geom_smooth(method = lm)
# generally higher ecoli in shallower lakes

```

```{r watershed data}

setwd("G:/My Drive/Research/watersheds/output")

ws1 <- read.csv("ws_metrics_combined_fixed.csv") %>% # missing a lot of them
  rename(dow = DOW)%>%
  mutate(dow = fixlakeid(dow))


ws2 <- read.csv("ws_metrics_treecanopy_10-23-24.csv") %>%
  rename(dow = DOW)%>%
  mutate(dow = fixlakeid(dow))



beachws1 <- left_join(yearlyavgecolibybeach, ws1)
beachws2 <- left_join(yearlyavgecolibybeach, ws2)

ggplot(beachws2, aes(x=wsarea_sqkm, y=log10(avgEcoli))) +
  geom_point() + 
  geom_smooth() + 
  xlim(0,20)

ggplot(beachws2, aes(x=percRoad, y=log10(avgEcoli))) +
  geom_point() + 
  geom_smooth() 

ggplot(beachws1, aes(x=percAg, y=log10(avgEcoli))) +
  geom_point() + 
  geom_smooth() 

develplot <- ggplot(beachws1, aes(x=percDevel, y=log10(avgEcoli))) +
  geom_point() +
  xlab("% developed land use") +
  ylab("log yearly-average Ecoli (mpn/100mL)") + 
  theme_bw() +
  theme(text=element_text(size = 20))

setwd("G:/My Drive/Research/beaches/output/figures/")

ggsave("developedecoliplot.png", plot = develplot, width = 8, height = 5, units = "in")

  


```

```{r habs closures}

setwd("G:/Shared drives/MSP LTER - Public/Q2 - Lakes and Watersheds/Q2.2 - Lakes & Surface Waters/TCMA Lake Research/Research initiatives/Beaches/Processed data")

habs <- read.csv("MPRB_habs_081125.csv") %>%
  rename(date = Date) %>%
  mutate(date = as.Date(date)) %>%
  filter(!is.na(Microcystin_ugL)) %>%
  mutate(year = as.factor(year(date))) %>%
  mutate(jday = yday(date)) %>%
  mutate(week = week(date))

ggplot(habs, aes(x=date, y=Microcystin_ugL, color = BeachName)) +
  geom_point() + 
  geom_smooth(se = FALSE)


ggplot(habs, aes(x=jday, y=Microcystin_ugL, color = BeachName)) +
  geom_point() + 
  geom_smooth(se = FALSE)



habs %>%
  filter(DOW == "27001900") %>%
  ggplot(aes(x=jday, y=Microcystin_ugL, color = year)) +
    geom_point() + 
    geom_smooth(se = FALSE) + 
    scale_color_discrete()


habsclim <- left_join(habs, dclim)

ggplot(habsclim, aes(x=ante2dptot, y = log10(Microcystin_ugL))) + 
      geom_point() + 
      geom_smooth()


ggplot(habsclim, aes(x=ante2avgmaxt, y = log10(Microcystin_ugL))) + 
      geom_point() + 
      geom_smooth()

# what other climate parameters exist? --> look at literature

```

